# Compile options
VERBOSE=n
OPT=g
USE_NANO=y
SEMIHOST=n
USE_FPU=y

# Libraries
USE_LPCOPEN=y
USE_SAPI=y

# FreeRTOS options
USE_FREERTOS=n
FREERTOS_HEAP_TYPE=4

# FatFS for SD card
USE_FATFS=y
DEFINES+=FSSDC_CS_PORT=3
DEFINES+=FSSDC_CS_PIN=12
DEFINES+=FSSDC_SPI_SLOW_CLOCK=50000
DEFINES+=FSSDC_SPI_FAST_CLOCK=1000000
