= Introducción

En los últimos años, la interacción entre dispositivos electrónicos y el entorno cotidiano se ha visto fuertemente influenciada por tecnologías de comunicación inalámbrica de bajo costo y corto alcance --- mandos a distancia, sensores de movimiento, sistemas de alarma, controles de portones eléctricos y equipos de domótica son solo algunos ejemplos de dispositivos que utilizan protocolos simples basados en señales infrarrojas (IR) y radiofrecuencia (RF) en bandas ISM/SRD#footnote[Los _Short-range devices_ son dispositivos de baja potencia con poco rango de transmisión. De todas las bandas que los SRD utilizan comúnmente, las _Industrial, Scientific, and Medical_ son bandas abiertas para uso general.] para transmitir información de manera eficiente y económica. Estas tecnologías, aunque ampliamente difundidas, suelen ser percibidas por el usuario final como cajas negras: se utilizan sin comprender cómo se generan, cómo se codifican los datos ni cómo podrían integrarse en nuevos desarrollos.

El proyecto, llamado _Médium_, tiene como motivación principal acercar estas tecnologías al ámbito educativo, brindando una herramienta didáctica y práctica que permita captar, analizar, almacenar y replicar señales IR y RF --- un instrumento que le permita al usuario interactuar directamente con los distintos aparatos que tenga en su casa. También podría llegar a ser utilizado para realizar depuraciones no profesionales, como detectar si la comunicación entre dos dispositivos funciona correctamente.

El dispositivo propuesto integrará módulos de recepción y transmisión (para IR y RF), una unidad de almacenamiento local para registrar capturas y una interfaz física básica (pantalla y controles) que permita al usuario interactuar con las señales. Por ejemplo, este dispositivo podría ser utilizado para capturar y almacenar la señal de un control remoto de televisión. A partir de la señal guardada, el proyecto permitiría reproducirla con el mismo dispositivo para encender, apagar o cambiar de canal, replicando así la función original del control sin necesidad de contar físicamente con él.

El proyecto es innovador porque se ubica en un espacio intermedio entre los analizadores profesionales de protocolos (costosos y especializados) y las soluciones caseras que suelen limitarse a un único protocolo. El único caso de un dispositivo similar de venta libre es Flipper Zero @Flipper. Una herramienta compacta y portátil que integra múltiples capacidades: lectura y emulación de etiquetas RFID/NFC, recepción y transmisión en bandas RF, captura y reproducción de señales infrarrojas, interfaces GPIO para experimentar con periféricos y una interfaz local con pantalla y botones que facilita su uso en campo. Flipper Zero ha mostrado la utilidad de consolidar en un solo equipo funciones que antes requerían múltiples dispositivos y conocimientos especializados, y ha generado una comunidad activa que desarrolla firmware, librerías y casos de uso.

/*En términos de desafíos, el proyecto aborda distintos frentes:

- Técnico, por la necesidad de integrar la captura de señales analógicas/digitales con procesos de decodificación y almacenamiento en memoria.
- De software, ya que será necesario implementar rutinas de procesamiento que permitan identificar patrones y gestionarlos en forma estructurada.
- De experiencia de usuario, dado que la utilidad final del sistema dependerá de su facilidad de uso y claridad en la visualización de resultados.*/

En definitiva, la relevancia del proyecto radica en ofrecer una plataforma flexible y accesible para experimentar con tecnologías de comunicación de uso cotidiano, acercando a estudiantes, docentes y entusiastas al entendimiento de protocolos de transmisión inalámbrica básicos, y sentando las bases para aplicaciones futuras en domótica, control remoto y sistemas de seguridad.
