== Presupuesto

En la @tabla-presupuesto se detallan los precios de los componentes utilizados para el desarrollo del proyecto. Específicamente, cuánto costó cada componente en el momento de su compra (en pesos argentinos, obtenidos entre agosto y diciembre de 2025). Además, se aproximó el costo de una hora de trabajo de ingeniería en USD 10 #sym.approx ARS 14.000.

#figure(
  table(
    columns: 3,
    stroke: none,
    align: (center, left, right),
    table.hline(),
    table.header[*Cantidad*][*Componente*][*Presupuesto* [ARS]],
    table.hline(),
    table.cell(colspan: 3, align: left)[*Módulos y placas principales*],
    [1], [EDU-CIAA-NXP], [],
    [1], [Módulo CC1101], [16.189],
    [1], [Módulo microSD], [2.640],
    [1], [OLED 1.3" 128×64], [8.990],
    [1], [Módulo IR TSOP38438], [3.060],
    [1], [LED IR emisor], [350],
    table.cell(colspan: 3, align: left)[*Regulación y alimentación*],
    [1], [Banco de pilas], [6.600],
    [2], [Bornera 2 pines], [540],
    [2], [Condensador electrolítico], [800],
    [1], [Regulador 5V], [1.500],
    [1], [Diodo zener], [500],
    [1], [Capacitor], [100],
    [1], [Resistencia], [300],
    [2], [Diodo rectificador], [500],
    table.cell(colspan: 3, align: left)[*Conectores*],
    [1], [Conector hembra], [1.200],
    [2], [Tiras de pines macho], [4.000],
    [1], [Tiras de pines hembra], [1.000],
    table.cell(colspan: 3, align: left)[*Botonera*],
    [1], [_Joystick_], [2.500],
    [2], [Pulsadores], [400],
    [2], [Condensador], [200],
    [2], [Resistencia], [600],
    table.cell(colspan: 3, align: left)[*Para IR*],
    [1], [Condensador], [400],
    [1], [Transistor], [500],
    [2], [Resistencias], [600],
    table.hline(),
    table.cell(colspan: 2, align: left)[*Precio de componentes*], [53.569\$],
    table.cell(colspan: 2, align: left)[*288 Horas trabajadas*], [4.050.000\$],
    // suponiendo 2.25M por 160 h (1 mes) - 14062.5/h * 288h = 4.050.000
    table.cell(colspan: 2, align: left)[*Total*], [4.103.569\$],
  ),
  caption: [Insumos y componentes de Médium (_bill of materials_).],
) <tabla-presupuesto>
